name: make

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.owner.login != github.event.pull_request.base.repo.owner.login
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get -q update
      - run: sudo DEBIAN_FRONTEND="noninteractive" apt-get -qq --no-install-recommends dist-upgrade
      - run: sudo DEBIAN_FRONTEND="noninteractive" apt-get -qq --no-install-recommends install
                  ca-certificates curl gcc gettext libcurl4-openssl-dev libssl-dev python3-dev
      - run: curl -sSfO 'https://bootstrap.pypa.io/get-pip.py'
      - run: sudo python3 get-pip.py
      - run: sudo python3 -m pip install --upgrade pip setuptools wheel
      - run: python3 -m pip install --upgrade babel build
      - run: make
      - run: python3 -m build  # Stores .tar.gz and .whl files into ./dist
      - run: sudo python3 -m pip install .
      - run: sudo motioneye_init --skip-apt-update
      - run: i=0; until ss -tln | grep 8765; do [ $i -le 10 ] || exit 0; sleep 1; i=$(expr $i + 1); done
      - run: sudo systemctl status motioneye
      - run: sudo systemctl is-active motioneye
